# Generated by Django 3.2.7 on 2021-09-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='دسته بندی دامنه ')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی',
            },
        ),
        migrations.CreateModel(
            name='DomainModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=50, verbose_name='نام فارسی دامنه')),
                ('domain', models.CharField(max_length=50, verbose_name='نام انگلیسی دامنه')),
                ('domain_price', models.IntegerField(verbose_name='قیمت')),
                ('domain_category', models.ManyToManyField(to='home.CategoryModel', verbose_name='دسته بندی دامنه')),
            ],
            options={
                'verbose_name': 'دامنه',
                'verbose_name_plural': 'دامنه',
            },
        ),
    ]
