# Generated by Django 3.2.7 on 2021-09-21 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_domainmodel_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domainmodel',
            name='domain_category',
        ),
        migrations.DeleteModel(
            name='CategoryModel',
        ),
        migrations.DeleteModel(
            name='DomainModel',
        ),
    ]
