# Generated by Django 3.2.7 on 2021-09-21 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0003_auto_20210921_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی ',
                'verbose_name_plural': 'دسته بندی',
            },
        ),
        migrations.CreateModel(
            name='Suffix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام دسته بندی دامنه')),
            ],
            options={
                'verbose_name': 'پسوند دامنه',
                'verbose_name_plural': 'پسوند دامنه',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persian_name', models.CharField(max_length=50, verbose_name='نام دامنه به فارسی')),
                ('english_name', models.CharField(max_length=50, verbose_name='نام دامنه به انگلیسی')),
                ('content', models.BooleanField(default=False, verbose_name='محتوا')),
                ('description', models.TextField(verbose_name='توضیحات دامنه')),
                ('price', models.CharField(blank=True, max_length=50, null=True, verbose_name='قیمت دامنه')),
                ('agreement_price', models.BooleanField(default=False, verbose_name='قیمت توافقی')),
                ('top_domains', models.BooleanField(default=False, verbose_name='برترین دامنه ها')),
                ('category', models.ManyToManyField(to='home.Category', verbose_name='نام دسته بندی')),
                ('suffix_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.suffix', verbose_name='نام پسوند دامنه')),
            ],
            options={
                'verbose_name': 'دامنه',
                'verbose_name_plural': 'دامنه',
            },
        ),
    ]
